language: node_js

node_js:
  - '12'
  - '10'

script:
- npm test

install:
  - npm i -g npm@6.0.1
  - npm ci
  - npm run build

deploy:
  skip_cleanup: true
  provider: npm
  email: "$NPM_EMAIL_ADDRESS"
  api_key: "$NPM_API_KEY"
  on:
    tags: true

after_deploy:
  sleep 20 ;
  curl "https://www.webjars.org/deploy?webJarType=npm&nameOrUrlish=recheck-web-js&version=${TRAVIS_TAG:1}"
